### ISSUE TITLE
Failed to reconcile BentoDeployment: unable to get: yatai-deployment/network because of unknown namespace for the cache

### ISSUE THREAD

**Issue by tmyhu** [bentoml/yatai-deployment#130]
Following the installation instructions, when I create my first BentoDeployment I run into this error and the BentoDeployment is stuck as `Available: False`:
```
yatai-deployment-8586fcd67c-vtfsm manager 1.699404695103506e+09	ERROR	Failed to reconcile BentoDeployment.	{"controller": "bentodeployment", "controllerGroup": "serving.yatai.ai", "controllerKind": "BentoDeployment", "BentoDeployment": {"name":"example","namespace":"yatai"}, "namespace": "yatai", "name": "example", "reconcileID": "aa5d9fcb-9aa7-489d-b9e6-44f5ce1828e6", "bentoDeployment": "example", "namespace": "yatai", "error": "get domain suffix: failed to get configmap network: get configmap: unable to get: yatai-deployment/network because of unknown namespace for the cache", "errorVerbose": "unable to get: yatai-deployment/network because of unknown namespace for the cache
get configmap
github.com/bentoml/yatai-deployment/controllers.(*BentoDeploymentReconciler).generateDefaultHostname.func1
  /workspace/controllers/bentodeployment_controller.go:2750
github.com/bentoml/yatai-common/system.GetNetworkConfigConfigMap
  /go/pkg/mod/github.com/bentoml/yatai-common@v0.0.0-20231016054533-fb836e058cfb/system/network.go:12
github.com/bentoml/yatai-common/system.GetDomainSuffix
  /go/pkg/mod/github.com/bentoml/yatai-common@v0.0.0-20231016054533-fb836e058cfb/system/ingress.go:183
github.com/bentoml/yatai-deployment/controllers.(*BentoDeploymentReconciler).generateDefaultHostname
  /workspace/controllers/bentodeployment_controller.go:2744
github.com/bentoml/yatai-deployment/controllers.(*BentoDeploymentReconciler).generateIngressHost
 /workspace/controllers/bentodeployment_controller.go:2734
github.com/bentoml/yatai-deployment/controllers.(*BentoDeploymentReconciler).generateIngresses
  /workspace/controllers/bentodeployment_controller.go:2833
github.com/bentoml/yatai-deployment/controllers.(*BentoDeploymentReconciler).createOrUpdateIngresses
(...)
```
yatai-deployment installed with values:
```
    enableRestrictedSecurityContext: true
    network:
      domainSuffix: stg.int.phq.io
      automaticDomainSuffixGeneration: false  # to disable a job that would try to create ingress stuff
    bentoDeploymentAllNamespaces: false
    bentoDeploymentNamespaces: ['yatai', 'yatai-system']
```

Note that I do not want to use Ingress at all and have disabled it in the BentoDeployment via `spec.ingress.enabled` so network configmap should not even be needed?
