### ISSUE TITLE
Ability to configure tis secret for network layer

### ISSUE THREAD

**Issue by zifeo** [bentoml/yatai-deployment#87]
Currently, it does not seem to be able to set a secret for the ingress, and thus cert-manager cannot be used out of the box.

```yaml
layers:
  network:
    ingressClass: nginx
    ingressAnnotations:
      cert-manager.io/cluster-issuer: letsencrypt
    ingressPath: /
    ingressPathType: ImplementationSpecific
    tls: true # ← suggested
```
